### ISSUE TITLE
Many ssh <defunct>  then using library. 

### ISSUE THREAD

**Issue by neodiz** [apenella/go-ansible#139] opened 2024-02-29 14:23 UTC
Good afternoon. I think I found a problem in the library, a large number of child processes are not closed. Here is my example

`func ansible() error {
	fmt.Println("test")
	ansiblePlaybookConnectionOptions := &options.AnsibleConnectionOptions{
		User:       "inurmuhametov",
		SSHExtraArgs: "-o ControlPersist=360s",
		SCPExtraArgs: "-o ControlPersist=360s",
		SFTPExtraArgs: "-o ControlPersist=360s",
	}

	ansiblePlaybookOptions := &playbook.AnsiblePlaybookOptions{
		Inventory:  "<server>,",
		VerboseVVVV:true,
	}

	playbook := &playbook.AnsiblePlaybookCmd{
		Playbooks:         []string{
			"/tmp/performance.yml"},
		ConnectionOptions: ansiblePlaybookConnectionOptions,
		Options:           ansiblePlaybookOptions,
	}

	err := playbook.Run(context.TODO())
	if err !=nil {
		playbook = nil
		return err
	}
	playbook = nil
	return nil

}
func main()  {

	for ; ;  {
		ansible()
		time.Sleep(5 * time.Minute)
	}
}`

`
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0 1229188 6164 pts/0    Ssl+ 12:13   0:00 /app
root          17  0.0  0.0      0     0 ?        Zs   12:13   0:00 [ssh] <defunct>
root          18  0.0  0.0      0     0 ?        Zs   12:13   0:00 [ssh] <defunct>
root          64  0.0  0.0   7636  4192 pts/1    Ss   12:14   0:00 bash
root         102  0.0  0.0      0     0 ?        Zs   12:18   0:00 [ssh] <defunct>
root         103  0.0  0.0      0     0 ?        Zs   12:18   0:00 [ssh] <defunct>
root         393  0.0  0.0      0     0 ?        Zs   12:23   0:00 [ssh] <defunct>
root         394  0.0  0.0      0     0 ?        Zs   12:23   0:00 [ssh] <defunct>
root         437  0.0  0.0      0     0 ?        Zs   12:29   0:00 [ssh] <defunct>
root         438  0.0  0.0      0     0 ?        Zs   12:29   0:00 [ssh] <defunct>
root         481  0.0  0.0      0     0 ?        Zs   12:34   0:00 [ssh] <defunct>
root         482  0.0  0.0      0     0 ?        Zs   12:34   0:00 [ssh] <defunct>
root         525  0.0  0.0      0     0 ?        Zs   12:39   0:00 [ssh] <defunct>
root         526  0.0  0.0      0     0 ?        Zs   12:39   0:00 [ssh] <defunct>
root         569  0.0  0.0      0     0 ?        Zs   12:44   0:00 [ssh] <defunct>
root         570  0.0  0.0      0     0 ?        Zs   12:44   0:00 [ssh] <defunct>
root         613  0.0  0.0      0     0 ?        Zs   12:49   0:00 [ssh] <defunct>
root         614  0.0  0.0      0     0 ?        Zs   12:49   0:00 [ssh] <defunct>
root         657  0.0  0.0      0     0 ?        Zs   12:54   0:00 [ssh] <defunct>
root         658  0.0  0.0      0     0 ?        Zs   12:54   0:00 [ssh] <defunct>
root         701  0.0  0.0      0     0 ?        Zs   12:59   0:00 [ssh] <defunct>
root         702  0.0  0.0      0     0 ?        Zs   12:59   0:00 [ssh] <defunct>
root         745  0.0  0.0      0     0 ?        Zs   13:05   0:00 [ssh] <defunct>
root         746  0.0  0.0      0     0 ?        Zs   13:05   0:00 [ssh] <defunct>
root         789  0.0  0.0      0     0 ?        Zs   13:10   0:00 [ssh] <defunct>
root         790  0.0  0.0      0     0 ?        Zs   13:10   0:00 [ssh] <defunct>
root         833  0.0  0.0      0     0 ?        Zs   13:15   0:00 [ssh] <defunct>
root         834  0.0  0.0      0     0 ?        Zs   13:15   0:00 [ssh] <defunct>
root         877  0.0  0.0      0     0 ?        Zs   13:20   0:00 [ssh] <defunct>
root         878  0.0  0.0      0     0 ?        Zs   13:20   0:00 [ssh] <defunct>
root         921  0.0  0.0      0     0 ?        Zs   13:25   0:00 [ssh] <defunct>
root         922  0.0  0.0      0     0 ?        Zs   13:25   0:00 [ssh] <defunct>
root         965  0.0  0.0      0     0 ?        Zs   13:30   0:00 [ssh] <defunct>
root         966  0.0  0.0      0     0 ?        Zs   13:30   0:00 [ssh] <defunct>
root        1009  0.0  0.0      0     0 ?        Zs   13:35   0:00 [ssh] <defunct>
root        1010  0.0  0.0      0     0 ?        Zs   13:35   0:00 [ssh] <defunct>
root        1053  0.0  0.0      0     0 ?        Zs   13:41   0:00 [ssh] <defunct>
root        1054  0.0  0.0      0     0 ?        Zs   13:41   0:00 [ssh] <defunct>
root        1097  0.0  0.0      0     0 ?        Zs   13:46   0:00 [ssh] <defunct>
root        1098  0.0  0.0      0     0 ?        Zs   13:46   0:00 [ssh] <defunct>
root        1141  0.0  0.0      0     0 ?        Zs   13:51   0:00 [ssh] <defunct>
root        1142  0.0  0.0      0     0 ?        Zs   13:51   0:00 [ssh] <defunct>
root        1185  0.0  0.0      0     0 ?        Zs   13:56   0:00 [ssh] <defunct>
root        1186  0.0  0.0      0     0 ?        Zs   13:56   0:00 [ssh] <defunct>
root        1229  0.0  0.0      0     0 ?        Zs   14:01   0:00 [ssh] <defunct>
root        1230  0.0  0.0      0     0 ?        Zs   14:01   0:00 [ssh] <defunct>
root        1273  0.0  0.0      0     0 ?        Zs   14:06   0:00 [ssh] <defunct>
root        1274  0.0  0.0      0     0 ?        Zs   14:06   0:00 [ssh] <defunct>
root        1317  0.0  0.0      0     0 ?        Zs   14:11   0:00 [ssh] <defunct>
root        1318  0.0  0.0      0     0 ?        Zs   14:11   0:00 [ssh] <defunct>
root        1361  0.0  0.0      0     0 ?        Zs   14:16   0:00 [ssh] <defunct>
root        1362  0.1  0.0      0     0 ?        Zs   14:16   0:00 [ssh] <defunct>

`

**Comment by apenella** [comment] 2024-03-04 07:02
Hi @neodiz!
Thank you very much for raising that issue. I will take a look at this.
Just letting you know, I will work on fixing that over the v2.0.0. By the way, have you tried setting a cancel context instead of the TODO one?

I keep you updated!

**Comment by apenella** [comment] 2024-03-19 07:06
Hi @neodiz!
I could reproduce what you experienced, which allowed me to work on a solution to that issue. Unfortunately, I don't have a fix for that yet.
My first thought was that the go-ansible code did not manage properly the processes spawned by the process started by the library. I tried to set up the [SysProcAttr](https://pkg.go.dev/syscall#SysProcAttr) or create a process group to handle the child processes but any of those was a deterministic solution.

I have realized that when I executed the ansible-playbook it also left some SSH zombie processes, and that allowed me to explore new avenues.
The cause of my problem was that I executed the playbook inside a container without the init enabled (read [here](https://github.com/ansible/ansible/issues/49270)), so no one reaped zombie processes.

Please, can you provide me with the following information?
- Are you running Ansible within a container?
- As is said [here](https://groups.google.com/g/ansible-project/c/IQoTNwDBIiA/m/qiHUTgg31lkJ), Ansible sets the SSH `-tt` parameter and that could leave zombie process on your system, coming from the pseudo-tty. That parameter should be overwritten by adding the `-T` on the SSH extra arguments. Can you confirm if you still have zombie processes after setting the `-T` parameter?

Thank you very much!

**Comment by neodiz** [comment] 2024-03-19 11:12
Hi. Yes i use code on docker container.
About parameter i check. A very interesting situation. I recommend adding a
mention of this issue in the documentation. I work as a devops and custom
module developer and other developers will not be able to understand what
the problem is. This may affect your library's reputation even though it is
very good.

вт, 19 мар. 2024 г. в 10:06, apenella ***@***.***>:

**Comment by apenella** [comment] 2024-03-20 06:36
Hi @neodiz!
I understand that the issue has been solved and I could close the issue.
I will follow your recommendation and I will include a section in the documentation explaining that behaviour and how to solve this.

Thank you very much!

**Comment by apenella** [comment] 2024-04-04 05:54
Available in [v2.0.0-rc-3](https://github.com/apenella/go-ansible/releases/tag/v2.0.0-rc.3)

**Closed by apenella** 2024-04-04 05:54 UTC
Labels: documentation, v2.0.0

**Comment by aravindhp** [comment] 2025-04-12 01:00
I am noticing another variant of this issue. The Ansible playbook uses jump hosts for connecting to the final host. It looks like when `delegate_to` is used with jump hosts, it creates a chain of SSH processes. The main Ansible process spawns SSH processes, which in turn spawn other SSH processes. These intermediary processes aren't cleaned up properly and become zombies. At least this is the conjecture on my part as even adding the `-T` parameter is not helping. Am I on the correct track? I am not sure how to handle this scenario. Any pointers will be appreciated.

**Comment by apenella** [comment] 2025-04-14 05:46
Hi @aravindhp!
Let me try to reproduce this behaviour.

BTW, did you experienced this with Ansible playbook directly or only when you execute Ansible through `go-ansible`?

Thanks!

**Comment by aravindhp** [comment] 2025-04-14 16:14
>Let me try to reproduce this behaviour.

Thank you!

>did you experienced this with Ansible playbook directly or only when you execute Ansible through go-ansible?

Only when I execute the playbook using go-ansible in a container. I am using the [ubi9-init](https://catalog.redhat.com/software/containers/ubi9-init/6183297540a2d8e95c82e8bd) image

**Comment by aravindhp** [comment] 2025-04-15 22:33
I tried writing my own executor that tries to do a process group clean up once the context is canceled:
```go
func (e *ProcessAwareExecutor) Execute(ctx context.Context) error {
	if e.cmd == nil {
		return fmt.Errorf("no command to execute")
	}

	cmdStr, err := e.cmd.Command()
	if err != nil {
		return fmt.Errorf("error getting command: %w", err)
	}
	if len(cmdStr) == 0 {
		return fmt.Errorf("empty command")
	}

	cmd := exec.CommandContext(ctx, cmdStr[0], cmdStr[1:]...)

	cmd.Env = os.Environ()
	for name, value := range e.envVars {
		cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", name, value))
	}

	// Set up process group for proper cleanup
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid: true, // Create a new process group
	}

	// Set up IO
	if e.write != nil && !e.quietStdout {
		cmd.Stdout = e.write
	}

	if e.writeError != nil {
		cmd.Stderr = e.writeError
	}

	// Start the command
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("error starting command: %w", err)
	}

	// Get the process group ID for cleanup
	pgid := cmd.Process.Pid

	// Setup a goroutine to kill the process group when the context is done
	go func() {
		<-ctx.Done()
		// Kill all processes in the group on context cancellation
		killErr := syscall.Kill(-pgid, syscall.SIGTERM)
		slog.DebugContext(ctx, "Killing process group", "pgid", pgid, "error", killErr)
	}()

	// Wait for command completion
	err = cmd.Wait()

	// Ensure cleanup of process group, even if the command completed normally
	// This is critical for SSH processes with -W flag that might otherwise become zombies
	if cmd.Process != nil {
		killErr := syscall.Kill(-pgid, syscall.SIGTERM)
		slog.DebugContext(ctx, "Killing process group again", "pgid", pgid, "error", killErr)
	}

	if err != nil && e.errorEnricher != nil {
		return e.errorEnricher.Enrich(err)
	}

	return err
}
```
But that did not help. Not 100% sure of it though.

**Comment by aravindhp** [comment] 2025-04-16 23:06
This turned out to be user error 🤦🏽 I had misconfigured my Dockerfile and there was actually no PID 1 init process. My application was running as the PID 1 process causing this issue. Apologies for the noise 🙏🏽

**Comment by apenella** [comment] 2025-04-23 16:39
Hi @aravindhp! I'm glad to hear you find out the cause of your issue 😄
